// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarTEDLibruary.Entities
{
    public partial class School
    {
        public School()
        {
            Programs = new HashSet<Program>();
        }

        [Key]
        [StringLength(10)]
        [Unicode(false)]
        public string SchoolCode { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string SchoolName { get; set; }

        [InverseProperty(nameof(Program.SchoolCodeNavigation))]
        public virtual ICollection<Program> Programs { get; set; }
    }
}