// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using StarTEDLibruary.Entities;

namespace StarTEDLibruary.DAL
{
    public partial class StarTEDContext : DbContext
    {
        public StarTEDContext()
        {
        }

        public StarTEDContext(DbContextOptions<StarTEDContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramCourse> ProgramCourses { get; set; }
        public virtual DbSet<School> Schools { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Latin1_General_CI_AS");

            modelBuilder.Entity<Program>(entity =>
            {
                entity.HasOne(d => d.SchoolCodeNavigation)
                    .WithMany(p => p.Programs)
                    .HasForeignKey(d => d.SchoolCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.Programs_dbo.Schools_SchoolCode");
            });

            modelBuilder.Entity<ProgramCourse>(entity =>
            {
                entity.HasOne(d => d.Program)
                    .WithMany(p => p.ProgramCourses)
                    .HasForeignKey(d => d.ProgramID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_dbo.ProgramCourses_dbo.Programs_ProgramID");
            });

            modelBuilder.Entity<School>(entity =>
            {
                entity.HasKey(e => e.SchoolCode)
                    .HasName("PK_dbo.Schools");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}